services:
  forum-db:
    image: postgres:13
    container_name: forum-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: forum_logs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d forum_logs"]
      interval: 5s
      timeout: 5s
      retries: 5

  jenkins:
    build: ./jenkins
    container_name: jenkins
    depends_on:
      forum-db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # монтировать сокет Docker Desktop не нужно

volumes:
  pgdata:
  jenkins_home:
