FROM jenkins/jenkins:lts

USER root

# Устанавливаем все нужные пакеты, включая python3-venv
RUN apt-get update && \
    apt-get install -y \
      python3 \
      python3-pip \
      python3-venv \
      postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# symlink для python и pip
RUN ln -sf /usr/bin/python3 /usr/bin/python \
 && ln -sf /usr/bin/pip3   /usr/bin/pip

USER jenkins
