FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# Создаём принудительные ссылки: не упадёт, если файл уже есть
RUN ln -sf /usr/bin/python3 /usr/bin/python \
 && ln -sf /usr/bin/pip3   /usr/bin/pip

USER jenkins
