# jenkins/Dockerfile
FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# Создадим symlink, чтобы команда python и pip работали по привычным именам
RUN ln -s /usr/bin/python3 /usr/bin/python \
 && ln -s /usr/bin/pip3 /usr/bin/pip

USER jenkins
